DROP TABLE IF EXISTS booking;

DROP TABLE IF EXISTS booking_status;

DROP TABLE IF EXISTS shareit_item;

DROP TABLE IF EXISTS item_request;

DROP TABLE IF EXISTS shareit_user;

CREATE TABLE IF NOT EXISTS shareit_user (
    user_id Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    email varchar(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS shareit_item (
    item_id Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name varchar(50),
    description varchar,
    available boolean,
    owner Long,
    request Long
);

CREATE TABLE IF NOT EXISTS item_request (
    id Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar,
    requester Long,
    created date
);

CREATE TABLE IF NOT EXISTS booking (
    id Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_booking date,
    end_booking date,
    item Long,
    booker Long,
    status Long
);

CREATE TABLE IF NOT EXISTS booking_status (
    id Long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

ALTER TABLE shareit_item ADD FOREIGN KEY (owner) REFERENCES shareit_user (user_id);

ALTER TABLE item_request ADD FOREIGN KEY (requester) REFERENCES shareit_user (user_id);

ALTER TABLE booking ADD FOREIGN KEY (status) REFERENCES booking_status (id);

ALTER TABLE booking ADD FOREIGN KEY (booker) REFERENCES shareit_user (user_id);

ALTER TABLE booking ADD FOREIGN KEY (item) REFERENCES shareit_item (item_id);

ALTER TABLE shareit_item ADD FOREIGN KEY (request) REFERENCES item_request (id);
